#!/bin/sh

build_n_run() {
  CFLAGS="$CFLAGS" ./build || exit $?

  dir="$(dirname "$0")"
  abspath=$(realpath "$dir")

  . "$dir"/cflags
  cflags="$cflags -I$abspath -L$abspath"
  ldflags="$ldflags -loli"

  for f in $abspath/tests/*.c; do
    exedir="$(dirname $f)"
    olddir="$(pwd)"
    cd $exedir
    exename=$(basename $f | sed s/.c//g)
    echo "-----------------------------------------"
    echo ":: $exename (shared) $CFLAGS"
    echo ""
    $cc $cflags $(basename $f) $ldflags -o $exename
    cd "$olddir"
    LD_LIBRARY_PATH=. $exedir/$exename || exit $?
  done

  . "$dir"/cflags
  cflags="$cflags -I$abspath -DOLI_IMPLEMENTATION"

  for f in $abspath/tests/*.c; do
    exedir=$(dirname $f)
    olddir="$(pwd)"
    cd $exedir
    exename=$(basename $f | sed s/.c//g)
    exename="${exename}_s"
    echo "-----------------------------------------"
    echo ":: $exename (static) $CFLAGS"
    echo ""
    $cc $cflags $(basename $f) $ldflags -o $exename
    cd "$olddir"
    $exedir/$exename || exit $?
  done
}

CFLAGS=-m32 build_n_run || exit $?
CFLAGS="" build_n_run || exit $?

echo "-----------------------------------------"
echo "> all tests passed!"
